source 'https://github.com/CocoaPods/Specs.git'

target 'DZPageScrollView', :exclusive => true do
  pod "DZPageScrollView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DZPageScrollView", :path => "../"

  
end
